name: HQS build docs for all packages

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:

  build_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        default: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip maturin
        pip install qoqo_qiskit/[docs] qoqo_qiskit_devices/[docs]
    - name: build
      run: |
        # qoqo_qiskit
        cd qoqo_qiskit/docs
        python -m sphinx -T -E -b html . _build/html
        cd ../../
        cp -r ./qoqo_qiskit/docs/_build/html ./documentation/src/qoqo_qiskit_api
        # qoqo_qiskit_devices
        cd qoqo_qiskit_devices/docs
        python -m sphinx -T -E -b html . _build/html
        cd ../../
        cp -r ./qoqo_qiskit_devices/docs/_build/html ./documentation/src/qoqo_qiskit_devices_api
        # roqoqo_qiskit_devices
        cargo doc --no-deps --package=roqoqo_qiskit_devices
        cp -r ./target/doc/* ./documentation/src/roqoqo_qiskit_devices_api
        # Generating doc
        cd documentation/
        mdbook build
  
  publish_documentation:
    needs: build_docs
    runs-on: ubuntu-latest
    steps:
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: documentation